# Generated by Django 5.0 on 2023-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lda_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature1", models.FloatField()),
                ("feature2", models.FloatField()),
                ("label", models.CharField(max_length=255)),
            ],
        ),
    ]
