# Generated by Django 5.0 on 2023-12-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_lda", "0002_alter_lda_data_label"),
    ]

    operations = [
        migrations.RenameModel(old_name="lda_data", new_name="LdaData",),
    ]
