# Generated by Django 5.0 on 2023-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_lda", "0004_ldadatainput_delete_ldadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldadatainput",
            name="species",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
