# Generated by Django 5.0 on 2023-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_lda", "0005_alter_ldadatainput_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldadatainput",
            name="species",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
