# Generated by Django 5.0 on 2023-12-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_lda", "0007_ldadata_delete_ldadatainput"),
    ]

    operations = [
        migrations.RenameModel(old_name="LdaData", new_name="LdaInput",),
    ]
